### ISSUE TITLE
妙用 Gitlab 解决 Github 无法 push

### ISSUE THREAD

**Issue by YuanJ2003** [YuanJ2003/YuanJ2003#1]
## 前言

由于众所周知的网络原因，在向 Github 提交代码时经常会出现 443 超时的情况，使用代理的话一方面长期可以稳定使用的代理大都需要付费，另一方面代理有时候使用也是不太方便的，比如我是在 WSL2 下使用的 git，如果要使用 Windows 下的代理就需要单独配置网络，但有时如果 Windows 下不开代理的话，WSL2 下的网络可能也会出现一些问题，而 Gitlab 在国内的访问速度比较稳定，一般都能够成功 push 或者 clone，所以我就将 GitHub 的代码都放到 Gitlab，然后使用 Gitlab 的镜像仓库同步推送到 GitHub，避免了部分网络问题

## 创建目标仓库

例如我的 npm 包，原本是直接提交到 GitHub，然后 GitHub Action 会自动发布到 npm，现在我将整个仓库 clone 到本地，再 push 到 Gitlab，然后再镜像同步到 GitHub 由 GitHub Action 进行自动发布，听上去挺麻烦，实际上我们只需要把仓库放到 Gitlab，设置好镜像同步即可，其它的都会自动进行

现在 GitHub 创建一个空白仓库用于接收，然后点击右上角头像—settings—Developer Settings—Personal access tokens 这里创建一个 token

![](https://images.hieroglyphs.top/2023/06/22/20230622214443.png)

一定记得，必须要勾选 repo 保证 token 具有仓库读写权限

![](https://images.hieroglyphs.top/2023/06/22/20230622214649.png)

## 设置镜像仓库

现在打开 Gitlab 的项目仓库页面，点击左下角的 设置—仓库—镜像仓库

![](https://images.hieroglyphs.top/2023/06/22/20230622214938.png)

展开之后输入刚刚创建的仓库的 url，密码为刚刚创建的 token

![](https://images.hieroglyphs.top/2023/06/22/20230622215028.png)

这里需要注意的是，仓库 url 需要包含你的 GitHub 用户名，例如我的用户名为 YuanJ2003，那么就需要在 url 的`github`前面加上`YuanJ2003@`

完整的 url 就为

```url
https://YuanJ2003@github.com/YuanJ2003/package.git
```

设置完成后，点击`镜像仓库`然后立即同步即可

![](https://images.hieroglyphs.top/2023/06/22/20230622215255.png)

同步过去的仓库与我们正常 push 的仓库没有区别，我用了挺长一段时间了没有任何问题，GitHub Action 照常运行，下面是我所用的 GitHub Action 配置文件

```yml
name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
```

同样，我们也可以用这个方法来给仓库进行备份，镜像到 Gitee 或者其它仓库
