### ISSUE TITLE
借用 CI/CD 自动化鉴定基因家族

### ISSUE THREAD

**Issue by YuanJ2003** [YuanJ2003/YuanJ2003#8]
>我们通常在进行基因家族鉴定时，需要使用 hmmer 来搜索某一基因的同源基因，尤其是具有相同结构域并且同源程度足够高的基因，我们会将其暂且定为一个基因家族，但 hmmer 安装、hmmbuild、hmmsearch 这些步骤通常是很简单的，但有些时候又会比较繁琐，加之后面需要筛选基因，收集蛋白质序列，这个过程不易消耗太多时间，于是乎，我写了一个项目，借用 Gitlab runner or Github Action 自动化查找同源基因并提取 ID 与蛋白质序列

极狐 Gitlab 仓库地址：https://jihulab.com/YuanJ2003/auto-hmmer

GitHub 仓库地址：https://github.com/YuanJ2003/auto-hmmer

## 概述

该项目主要是通过 CI/CD 功能，拉取 Ubuntu 镜像，并且安装所需的软件，执行对应的 Python 程序，实现自动化，只需要在`input.py`中输入 pfam 网站上的 PF 编号、阈值范围和物种即可，仓库中我只存放了水稻、拟南芥和玉米的蛋白质序列，其他物种的序列，自行上传后更改`input.py`中的物种变量即可

## Python 程序

五个 Python 程序分别执行不同的功能、通常上一程序执行完毕才能顺利执行下一个程序

### input.py

```python
PF_number = "PF00031"

evaluation_threshold = "1e-5"

species = "Oryza_sativa"

## The repository only contains the genome protein sequences of three species: Arabidopsis_thaliana , Oryza_sativa , and Zea_mays
```

这里是定义全局变量，将其整合在一个文件中，便于输入

### data_preparation.py

```python
import requests
import input

hmm = "http://pfam-legacy.xfam.org/family/{}/hmm".format(input.PF_number)  ## 文件的 URL 地址

hmm_content = requests.get(hmm)  ## 发送 GET 请求获取文件内容

hmm_content = hmm_content.text  ## 获取文件的文本内容

hmm_file = open("build.hmm", "w")

hmm_file.write(hmm_content)

hmm_file.close()

PFseed = "http://pfam-legacy.xfam.org/family/{}/alignment/seed/format?format=stockholm&alnType=seed&order=t&case=l&gaps=default&download=1".format(input.PF_number)

PFseed_content = requests.get(PFseed)  ## 发送 GET 请求获取文件内容

PFseed_content = PFseed_content.text  ## 获取文件的文本内容

PFseed_file = open("PFseed.txt", "w")

PFseed_file.write(PFseed_content)

PFseed_file.close()
```

这里是通过调用 requests 库来下载因隐马尔可夫模型文件和 Stockholm file，为 hmmer 建立模型、搜索基因做准备

### hmmer.py

```python
import subprocess
import input

def run_command(command):
    process = subprocess.Popen(command, stdout=subprocess.PIPE, shell=True) 
    output, error = process.communicate() 

    if process.returncode != 0:
        print(f'Error occurred: {error}')
    else:
        print(f'Success!\n{output}')

## 创建你的命令
hmmbuild_command = 'hmmbuild build.hmm PFseed.txt'
hmmsearch_command = 'hmmsearch build.hmm ./protein_sequence/{}.fasta > result.out'.format(input.species)

## 运行你的命令
run_command(hmmbuild_command)
run_command(hmmsearch_command)
```

这个程序通过调用 subprocess 库来执行系统命令，使用 hmmer，在此执行此程序之前，已经自动安装好 hmmer 并加入到环境变量中，可以在这个文件中自定义 hmmer 命令

### extract_id.py

```python
import re
import os
import input

file_path = os.path.expanduser('./result.out') 

output_path = os.path.expanduser('./id_list.txt')  

with open(file_path, 'r') as file:
    data = file.readlines()

## Pattern to match evalue anywhere in the string
pattern = re.compile('\d+e-[0-9]{2}', re.IGNORECASE)

process_data = True

## Prepare the output file
with open(output_path, 'w') as out_file:
    for line in data:
        if '------ inclusion threshold ------' in line:
            process_data = False

        if process_data:
            match = pattern.search(line)
            if match:
                e_value = float(match.group())

                if e_value < float(input.evaluation_threshold) :
                    parts = line.split()
                    out_file.write(parts[-1] + '\n')  ## Write Sequence gene id to file
```

这个程序将从 hmmsearch 的结果文件`result.out`中筛选出符合我们设定的阈值的基因 ID，写入`id_list.txt`

### extract_sequence.py

```python
from Bio import SeqIO
from input import species

def extract_sequences(id_list, fasta_file, out_file):
    with open(id_list, 'r') as id_handle, open(out_file, 'w') as out_handle:
        ids = [line.strip() for line in id_handle.readlines()]
        fasta_sequences = SeqIO.parse(open(fasta_file),'fasta')

        for fasta in fasta_sequences:
            name, sequence = fasta.id, str(fasta.seq)
            if name in ids:
                SeqIO.write(fasta, out_handle, 'fasta')

extract_sequences('id_list.txt', "./protein_sequence/{}.fasta".format(species), 'protein_for_target_id.fasta')
```

这个程序将从蛋白质序列文件中提取出上一步筛选出的 ID 的蛋白质序列，使用了 biopython 库，将提取的序列写入`protein_for_target_id.fasta`

### .gitlab-ci.yml

```yml
default:
  image:  ubuntu:latest

stages:
  - hmmer_search
  - extract_id
  - extract_sequence

hmmer_search:
  stage: hmmer_search
  before_script:
    - sed -i 's@//.*archive.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list
    - apt-get update && apt-get install -y build-essential gcc python3 python3-pip
    - pip install requests -i https://mirrors.aliyun.com/pypi/simple/
    - tar -xvf hmmer.tar.gz
    - cd hmmer-3.3.2
    - ./configure
    - make
    - make install
    - export PATH="$PATH:~/hmmer-3.3.2/bin"
    - cd ..
  script:
    - python3 data_preparation.py
    - python3 hmmer.py
  artifacts:
    paths:
      - build.hmm
      - PFseed.txt
      - result.out
  only:
    - main

extract_id:
  stage: extract_id
  before_script:
    - sed -i 's@//.*archive.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list
    - apt-get update && apt-get install python3 -y
  script:
    - chmod +x extract_id.py
    - python3 extract_id.py
  artifacts:
    paths:
      - id_list.txt
  only:
    - main

extract_sequence:
  stage: extract_sequence
  before_script:
    - sed -i 's@//.*archive.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list
    - apt-get update && apt-get install python3-pip -y
    - pip install biopython -i https://mirrors.aliyun.com/pypi/simple/
  script:
    - chmod +x extract_sequence.py
    - python3 extract_sequence.py
  artifacts:
    paths:
      - protein_for_target_id.fasta
  only:
    - main
```

这是 Gitlab CI/CD 的配置文件，分为 hmmer 搜索、ID 提取、序列提取三个步骤，并上传每个步骤的结果作为产物

### .github/workflows/auto-hmmer.yml

```yml
name: CI

on:
  push:
    branches:
      - main

jobs:
  hmmer_search:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential gcc python3 python3-pip
          pip install requests
          tar -xvf hmmer.tar.gz
          cd hmmer-3.3.2
          ./configure
          make
          sudo make install
          export PATH="$PATH:~/hmmer-3.3.2/bin"
          cd ..
      - name: Run scripts
        run: |
          python3 data_preparation.py
          python3 hmmer.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: hmmer-out
          path: |
            build.hmm
            PFseed.txt
            result.out

  extract_id:
    needs: hmmer_search
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download result.out
        uses: actions/download-artifact@v2
        with:
          name: hmmer-out
          path: ./
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install python3 -y

      - name: Run scripts
        run: |
          sudo chmod +x extract_id.py
          python3 extract_id.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: id-list
          path: |
            id_list.txt

  extract_sequence:
    needs: extract_id
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download id_list.txt
        uses: actions/download-artifact@v2
        with:
          name: id-list
          path: ./
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install python3-pip -y
          pip install biopython

      - name: Run scripts
        run: |
          sudo chmod +x extract_sequence.py
          python3 extract_sequence.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: sequence-data
          path: |
            protein_for_target_id.fasta
```

这是 GitHub Action 的配置文件，也分为 hmmer 搜索、ID 提取、序列提取三个步骤，并上传每个步骤的结果作为产物

## 使用

直接 fork 我的仓库，极狐 Gitlab/GitHub 的都一样，当然，极狐 Gitlab 的仓库也同样适用于全球版 Gitlab 与自托管的 Gitlab，前提是你要有使用 Gitlab runner 的权限

修改`input.py`中的三个变量即可

如果需要更多物种，上传蛋白质序列到 protein_sequence 文件夹，并且修改`input.py`中的物种变量即可，需要注意的是，变量的内容需要与蛋白质序列文件名称相同，但不包含后缀名

运行的结果与输出文件，下载对应流水线步骤的产物即可

![](https://images.hieroglyphs.top/2023/07/23/20230723000504.png)

![](https://images.hieroglyphs.top/2023/07/23/20230723000524.png)
